---
# handlers file for zabbix-server
#
- name: Restart zabbix-server apache2 postgresql handler
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - zabbix-server
    - postgresql
    - apache2 

