---
# handlers file for zabbix-server-role
#
- name: Restart zabbix-server apache2 postgresql handler
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - zabbix-server
    - postgresql
    - apache2 

