---
# tasks file for zabbix-agent-role

- name: Download and install zabbix repository from official .deb package
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb

- name: Update repositories cache and install "zabbix-agent" package
  apt:
    name: zabbix-agent
    update_cache: yes
    state: present

- name: Create list of updates for /etc/zabbix/zabbix_agentd.conf
  set_fact:
    agent_config_updates:
      - { regexp: '^Server=127.0.0.1$', replace: "Server={{ zabbixPRIVATEip }}" }
      - { regexp: '^ServerActive=127.0.0.1$', replace: "ServerActive={{ zabbixPRIVATEip }}" }
      - { regexp: '^Hostname=Zabbix server$', replace: "Hostname={{ ansible_hostname }}" }
      - { regexp: '^# HostMetadata=$', replace: 'HostMetadata=Linux servers' }
      - { regexp: '^# HostInterface=$', replace: "HostInterface={{ ansible_default_ipv4.address }}" }

- name: Update /etc/zabbix/zabbix_agentd.conf with the list of updates
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items: "{{ agent_config_updates }}"
  notify:
    - Restart zabbix-agent handler

- name: Start zabbix-agent and make it enabled on boot.
  service:
    name: zabbix-agent
    state: started
    enabled: yes