---
# tasks file for zabbix-agent-role

- name: Download and install zabbix repository from official .deb package
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb

- name: Update repositories cache and install "zabbix-agent" package
  ansible.builtin.apt:
    name: zabbix-agent
    update_cache: yes
    state: present

- name: Update /etc/zabbix/zabbix_agentd.conf with the list of updates
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^Server=127.0.0.1$', replace: "Server={{ hostvars['ZABBIX']['ansible_host'] }}" }
    - { regexp: '^ServerActive=127.0.0.1$', replace: "ServerActive={{ hostvars['ZABBIX']['ansible_host'] }}" }
    - { regexp: '^Hostname=Zabbix server$', replace: "Hostname={{ ansible_hostname }}" }
    - { regexp: '^# HostMetadata=$', replace: 'HostMetadata=Linux servers' }
    - { regexp: '^# HostInterface=$', replace: "HostInterface={{ ansible_default_ipv4.address }}" }
  notify:
    - Restart zabbix-agent handler

- name: Start zabbix-agent and make it enabled on boot.
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: yes