---
- name: Terraform lesson 2 task 2 (equip 1 server with nginx via Ansible).
  hosts: cloud_webservers
  become: true  
  roles:
    - nginx-role

- name: Terraform lesson 2 task 2 (equip 1 server with PostgreSQL database via Ansible).
  hosts: cloud_dbservers
  become: true
  tasks:
  - name: Insall PostreSQL.
    apt:
      update_cache: true
      name: 
        - postgresql
      state: present
  - name: Start PostgreSQL and make it enabled on boot.
    service:
      name: postgresql
      state: started
      enabled: yes   

- name: Terraform lesson 2 task 2. 
  hosts: cloud_machines
  become: true
  tasks:
  - name: Check status of the services.
    service_facts:
    register: output

  - debug:
      msg: 
        - 'Nginx state is {{ output.ansible_facts.services["nginx.service"].state }}'
    when: "'cloud_webservers' in group_names"

  - debug:
      msg: 
        - 'PostgreSQL state is {{ output.ansible_facts.services["postgresql@13-main.service"].state }}'   
    when: "'cloud_dbservers' in group_names"
