---
# tasks file for filebeat-role

- name: Download and install filebeat from .deb package  (source - yandex mirror)
  apt:
    deb: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.10.3-amd64.deb

#- name: Configure Filebeat  (Make zabbix.conf.php and place it in /etc/zabbix/web/)
#  template:
#    src: filebeat.yml.j2
#    dest: /etc/filebeat/filebeat.yml
#    notify: Restart filebeat handler

#- name: Start Filebeat service
#  service:
#    name: filebeat
#    state: started
#    enabled: yes