---
# tasks file for elasticsearch-role

- name: Download and install elasticsearch from .deb package  (source - yandex mirror)
  apt:
    deb: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.10.3-amd64.deb
  register: installation_result

- name: Print elasticsearch installation output
  debug:
    var: installation_result.stdout

- name: Check if certificate folder elastic-mycert already exists
  stat:
    path: /etc/elasticsearch/certs/elastic-mycert.d
  register: folder_check  

- name: Create certificates and place them as per configuration file elasticsearch.yml
  block:

    - name: Create /tmp/make-certs.sh locally
      become: false
      template:
        src: make-certs.sh.j2
        dest: /tmp/make-certs.sh
      delegate_to: localhost

    - name: Run make-certs.sh on the elasticsearch-server
      script: /tmp/make-certs.sh 
      args:
        executable: bash

  when: not folder_check.stat.exists

- name: Pick up certificates for kibana-role from elasticsearch-server to local machine
  fetch:
    src: "{{ item }}"
    dest: ~/ansible/kibana-role/files/
    flat: yes
  loop:
    - "/tmp/kibana-mycert.d.zip"
    - "/etc/elasticsearch/certs/ca.d/ca.crt"

- name: Configure elasticsearch (Make elasticsearch.yml and place it in /etc/elasticsearch/)
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch handler

- name: Start elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes